# This file is a sample configuration file for cgpt.

# # The backend to use.
# backend: "openai"
# # The model to use.
# model: "gpt-4o"
# # Whether or not to stream output.
# stream: true
# Optional system prompt.
# systemPrompt: "You are a helpful programming assistant. Your output MUST always be valid JSON blobs"
# Maximum tokens to return (including input).
#maxTokens: 2048
